"""
inject_report.py -- insert RTL + PPA + on-chip results into the IEEE report.
New content is coloured blue and bracketed with [NEW ADDITION] markers.
Output: Bias_Aware_Approximate_MAC_IEEE_v2.docx
"""
from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from copy import deepcopy
import re

SRC = "E:/AIDev/EEC 289Q 002 SQ 2026：Deep Learning Hardware/project/FromTeamMate/Bias_Aware_Approximate_MAC_IEEE(1).docx"
DST = "E:/AIDev/EEC 289Q 002 SQ 2026：Deep Learning Hardware/project/Bias_Aware_Approximate_MAC_IEEE_v2.docx"

BLUE = RGBColor(0x00, 0x44, 0xCC)

doc = Document(SRC)

# ------------------------------------------------------------------ helpers --

def add_blue_para(doc, text, bold=False, size=10):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.color.rgb = BLUE
    run.font.bold = bold
    run.font.size = Pt(size)
    return p

def insert_paragraph_before(ref_para, new_para_element):
    """Insert new_para_element (lxml element) before ref_para in the document."""
    ref_para._p.addprevious(new_para_element)

def blue_para_element(doc, text, bold=False, size=10, style="Normal"):
    """Return an lxml paragraph element with blue text, not yet attached."""
    p = doc.add_paragraph()          # temporary – we'll detach it
    p.style = doc.styles[style]
    run = p.add_run(text)
    run.font.color.rgb = BLUE
    run.font.bold = bold
    run.font.size = Pt(size)
    element = p._p                   # grab lxml element
    p._p.getparent().remove(p._p)    # detach from document body
    return element

# ------------------------------------------- locate insertion points ---------

paras = doc.paragraphs
v_results_idx  = next(i for i, p in enumerate(paras) if "V. RESULTS" in p.text)
vi_limits_idx  = next(i for i, p in enumerate(paras) if "VI. LIMITATIONS" in p.text)

v_results_para  = paras[v_results_idx]
vi_limits_para  = paras[vi_limits_idx]

# ====================================================
# BLOCK 1 – RTL IMPLEMENTATION section
# inserted before V. RESULTS AND DISCUSSION
# ====================================================

rtl_lines = [
    ("[NEW ADDITION — RTL Hardware Implementation]", True, 9),
    ("V-A. RTL Implementation", True, 10),
    (
        "The AxMAC MAC unit is implemented in synthesizable Verilog (Quartus Prime Lite 18.1) "
        "targeting the Intel Cyclone IV E EP4CE10F17C8 FPGA on the EmbedFire 野火征途 Pro board. "
        "The design is organized as a four-level hierarchy: mac_unit (one signed multiplier with "
        "K-bit truncation and rounding control), aca_adder (accuracy-configurable adder with "
        "carry window W), mac_array (R×C systolic tile, default R=1, C=4 parallel PEs), "
        "mlp_top (two-layer MLP 64→16→10 with weight ROM), and mlp_top_demo (board wrapper: "
        "argmax → 4 active-low LEDs + 115200-baud UART TX on PIN_B3). "
        "All three rounding modes (trunc/round/stochastic) and the ACA window are configurable "
        "at synthesis time via Verilog parameters K_PARAM, MODE, and ACA_W. "
        "Five ModelSim testbenches (tb_mac_unit, tb_aca_adder, tb_mac_array, tb_mlp_top, "
        "tb_mlp_top_demo) pass in simulation (2026-06-01). "
        "The synthesized design occupies 21% of EP4CE10 logic elements with timing closure at 50 MHz.",
        False, 10,
    ),
]

for text, bold, size in reversed(rtl_lines):
    el = blue_para_element(doc, text, bold=bold, size=size)
    insert_paragraph_before(v_results_para, el)

# ====================================================
# BLOCK 2 – PPA table + on-chip results
# appended inside V. RESULTS (before VI. LIMITATIONS)
# ====================================================

results_lines = [
    ("[NEW ADDITION — Hardware Synthesis and On-Chip Results]", True, 9),
    ("V-B. Hardware Synthesis Results (PPA)", True, 10),
    (
        "Table I shows post-fit resource and power results on EP4CE10 for the three rounding "
        "modes at K=6, ACA_W=32 (exact accumulator), generated by Quartus Prime PowerPlay. "
        "Plain truncation (trunc) saves 84 logic elements (LE) and 17% core dynamic power "
        "versus the exact K=0 baseline (1769 LE, 10.45 mW). "
        "The round mode (add constant 2^(K-1) before masking) recovers near-zero-mean bias "
        "at a cost of only +46 LE and zero extra registers — the correction constant folds "
        "into the partial-product tree with no state. "
        "Stochastic rounding requires a 64-bit LFSR (+132 LE, +64 registers); at K=6 this "
        "erases all area savings (1817 LE > 1769 exact baseline). "
        "This confirms Contribution A on real hardware: round achieves near-zero bias at "
        "~35% of stochastic's added cost with zero register overhead.",
        False, 10,
    ),
    (
        "Table I — Rounding-mode hardware cost (K=6, ACA_W=32, EP4CE10F17C8)",
        True, 9,
    ),
    (
        "  Configuration         | Logic Elems | Registers | DSP | Core Power (mW)\n"
        "  Exact (K=0, baseline) |    1769     |    582    |  4  |     10.45\n"
        "  K=6, trunc            |    1685     |    527    |  4  |      8.67\n"
        "  K=6, round            |    1731     |    527    |  4  |      9.20\n"
        "  K=6, stochastic       |    1817     |    591    |  4  |      9.39",
        False, 9,
    ),
    ("V-C. On-Chip Experimental Results", True, 10),
    (
        "Five bitstreams were programmed onto the EP4CE10 via JTAG (USB-Blaster). "
        "Each configuration uses the same fixed 64-dimensional input vector and golden weights. "
        "The 4-LED argmax display was observed after each burn. "
        "The reference exact result is argmax = 1 "
        "(logits ≈ [4345, 10718, −4421, −9026, −3228, −6422, 4780, −3136, 10420, 6344]).",
        False, 10,
    ),
    (
        "Table II — On-chip argmax vs. configuration (EP4CE10, 野火征途 Pro, 2026-06-01)",
        True, 9,
    ),
    (
        "  Config    | K | Mode  | Board argmax | Correct\n"
        "  K0_trunc  | 0 | trunc |      1       |   YES\n"
        "  K2_trunc  | 2 | trunc |      1       |   YES\n"
        "  K4_trunc  | 4 | trunc |      1       |   YES\n"
        "  K4_round  | 4 | round |      1       |   YES\n"
        "  K6_trunc  | 6 | trunc |      3       |   NO  <- misclassified",
        False, 9,
    ),
    (
        "Configurations K=0/2/4 (trunc) and K=4 (round) all produce the correct argmax = 1, "
        "demonstrating AxMAC robustness under moderate approximation. "
        "K=6 trunc shifts argmax to class 3 — a misclassification consistent with the "
        "Python simulation result (accumulated bias +29.9 at K=6), where the bias is "
        "sufficient to invert the two closest logits (margin = 10718 − 10420 = 298). "
        "K=4 round and K=4 trunc give identical argmax, validating that round's "
        "near-zero-mean bias keeps the rank ordering intact at this truncation depth. "
        "All five hardware results match the corresponding Python simulation predictions, "
        "confirming RTL implementation correctness.",
        False, 10,
    ),
]

for text, bold, size in reversed(results_lines):
    el = blue_para_element(doc, text, bold=bold, size=size)
    insert_paragraph_before(vi_limits_para, el)

# ====================================================
# BLOCK 3 – note at top of document
# ====================================================

note_el = blue_para_element(
    doc,
    "[REVISION NOTE 2026-06-01: Blue text = new additions. "
    "Added: RTL implementation section, hardware synthesis PPA table (Table I), "
    "and on-chip experimental results table (Table II).]",
    bold=True, size=9
)
doc.paragraphs[0]._p.addprevious(note_el)

# ---------------------------------------------------- save --------------------
doc.save(DST)
print("Saved: Bias_Aware_Approximate_MAC_IEEE_v2.docx")
